### PR TITLE
fix: useToggleHandler `ESC` propagation handling

### LINKED ISSUE #107: Escape key event `defaultPrevented` when kbar is mounted
Preventing default at all times… this is breaking keyboard handler behavior elsewhere.

https://github.com/timc1/kbar/blob/main/src/InternalEvents.tsx#L40

### PR DESCRIPTION
**Pull request by timc1**
Closes #107.

Fixes an issue where hitting `ESC` would not only close kbar, but the event would propagate to other listeners; i.e. you have a modal open behind kbar. Hitting `ESC` would hide kbar and toggle the modal.

### CODE REVIEW

File: example/src/App.tsx [hunk 1]
```diff
@@ -249,3 +250,25 @@ function HomeIcon() {
     </svg>
   );
 }
+
+function FakeModal() {
```
Comment (timc1) [inline example/src/App.tsx:254]: POC, deleting before merge.

File: src/InternalEvents.tsx [hunk 2]
```diff
@@ -47,9 +49,9 @@ function useToggleHandler() {
       }
     }
 
-    window.addEventListener("keydown", handleKeyDown);
-    return () => window.removeEventListener("keydown", handleKeyDown);
-  }, [query]);
+    window.addEventListener("keydown", handleKeyDown, true);
+    return () => window.removeEventListener("keydown", handleKeyDown, true);
```
Comment (timc1) [inline src/InternalEvents.tsx:53]: 🍖  Setting `useCapture` to `true` here makes sure that this `keydown` event will fire before others, even when other `keydown` event listeners are registered higher up in the DOM tree. 

This ensures our `event.stopPropagation` actually stops the event from being captured by, say, a modal that is open behind kbar.

File: src/InternalEvents.tsx [hunk 3]
```diff
@@ -17,8 +17,9 @@ export default function InternalEvents() {
  * `useToggleHandler` handles the keyboard events for toggling kbar.
  */
 function useToggleHandler() {
-  const { query, options, visualState } = useKBar((state) => ({
+  const { query, options, visualState, hidden } = useKBar((state) => ({
     visualState: state.visualState,
+    hidden: state.visualState !== VisualState.showing,
```
Comment (tommoor) [inline src/InternalEvents.tsx:22]: Probably just flip this to visible? As it's flipped here and flipped back in the guard

**Review by tommoor — APPROVED** [review]
